### ISSUE TITLE
I2C Clock is On During Data-Taking?

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/OptoHybridv2#17]
Using firmware version: optohybrid_top_16-06-2016.bit
Using Web DAQ
Clock Source: GTX recovered clock
Sequence: Start all VFATs -> Apply Default Parameters -> Threshold scan on VFAT12.  First attachment (VFAT12_ThreshScan_FW_16-06-2016.png)
<img width="757" alt="vfat12_threshscan_fw_16-06-2016" src="https://cloud.githubusercontent.com/assets/6432141/17254441/2c70d022-55b5-11e6-8301-581af8688f07.png">
Notice long tail in threshold scan distribution

Using firmware version: optohybrid_top_23-03-2016-I2C.bit
Using Web DAQ
Same clock source as above
Same sequence as above
No tail in threshold scan for VFAT12.  See second attachment (VFAT12_ThreshScan_FW_23-03-2016)
<img width="755" alt="vfat12_threshscan_fw_23-03-2016" src="https://cloud.githubusercontent.com/assets/6432141/17254513/70d3fa3c-55b5-11e6-8df2-93aad7ec8703.png">

Is the I2C clock running when it shouldn't be in the optohybrid_top_16-06-2016.bit firmware? Note this firmware has the expanded SBIT functionality for the cosmic stand.

**Comment by thomaslenzi** [comment]
Updated and fixed for GEB v2a and v2b
